### ISSUE TITLE
同步按钮组件的文档

### ISSUE THREAD

**Issue by luckyufei** [allanfish/f8#6]

**Comment by luckyufei** [comment]
List-Block Buttons 中按钮之间的线大小和f7的不一致. 因为f7中有这个: 

``` css
html.pixel-ratio-2 .list-block .item-link.list-button:after {
    -webkit-transform: scaleY(.5);
    transform: scaleY(.5)
}
```
